apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage